from __future__ import annotations
from agent.interfaces import Recipe, RecipeCandidate, UserProfile

MOCK_RECIPES = [
    Recipe(
        recipe_id=1001,
        title="Grilled Chicken Salad",
        ingredients=["chicken breast", "romaine lettuce", "cherry tomatoes", "cucumber", "olive oil", "lemon juice"],
        tags=["high_protein", "low_carb", "gluten_free"],
        cuisine="American",
        prep_minutes=10,
        cook_minutes=15,
        total_minutes=25,
        servings=2,
        calories=350.0,
        protein_g=35.0,
        carbs_g=12.0,
        fat_g=18.0,
        estimated_cost=8.50,
    ),
    Recipe(
        recipe_id=1002,
        title="Veggie Stir Fry",
        ingredients=["broccoli", "bell pepper", "carrot", "soy sauce", "garlic", "ginger", "rice"],
        tags=["vegetarian", "vegan"],
        cuisine="Asian",
        prep_minutes=10,
        cook_minutes=12,
        total_minutes=22,
        servings=2,
        calories=280.0,
        protein_g=8.0,
        carbs_g=45.0,
        fat_g=6.0,
        estimated_cost=5.00,
    ),
    Recipe(
        recipe_id=1003,
        title="Overnight Oats",
        ingredients=["rolled oats", "almond milk", "chia seeds", "honey", "blueberries"],
        tags=["vegetarian", "high_fiber"],
        cuisine="American",
        prep_minutes=5,
        cook_minutes=0,
        total_minutes=5,
        servings=1,
        calories=310.0,
        protein_g=10.0,
        carbs_g=52.0,
        fat_g=8.0,
        estimated_cost=3.00,
    ),
    Recipe(
        recipe_id=1004,
        title="Salmon with Asparagus",
        ingredients=["salmon fillet", "asparagus", "olive oil", "garlic", "lemon", "dill"],
        tags=["high_protein", "gluten_free", "pescatarian"],
        cuisine="Mediterranean",
        prep_minutes=10,
        cook_minutes=20,
        total_minutes=30,
        servings=2,
        calories=420.0,
        protein_g=38.0,
        carbs_g=8.0,
        fat_g=26.0,
        estimated_cost=12.00,
    ),
    Recipe(
        recipe_id=1005,
        title="Turkey Meatballs",
        ingredients=["ground turkey", "breadcrumbs", "egg", "garlic", "onion", "marinara sauce", "spaghetti"],
        tags=["high_protein"],
        cuisine="Italian",
        prep_minutes=15,
        cook_minutes=25,
        total_minutes=40,
        servings=4,
        calories=480.0,
        protein_g=32.0,
        carbs_g=42.0,
        fat_g=16.0,
        estimated_cost=9.00,
    ),
    Recipe(
        recipe_id=1006,
        title="Greek Yogurt Parfait",
        ingredients=["greek yogurt", "granola", "strawberries", "honey"],
        tags=["vegetarian", "high_protein"],
        cuisine="American",
        prep_minutes=5,
        cook_minutes=0,
        total_minutes=5,
        servings=1,
        calories=250.0,
        protein_g=18.0,
        carbs_g=35.0,
        fat_g=5.0,
        estimated_cost=3.50,
    ),
    Recipe(
        recipe_id=1007,
        title="Black Bean Tacos",
        ingredients=["black beans", "corn tortillas", "avocado", "salsa", "lime", "cilantro", "onion"],
        tags=["vegetarian", "vegan", "gluten_free"],
        cuisine="Mexican",
        prep_minutes=10,
        cook_minutes=10,
        total_minutes=20,
        servings=2,
        calories=380.0,
        protein_g=14.0,
        carbs_g=52.0,
        fat_g=12.0,
        estimated_cost=5.50,
    ),
    Recipe(
        recipe_id=1008,
        title="Chicken Stir Fry with Rice",
        ingredients=["chicken breast", "broccoli", "bell pepper", "soy sauce", "garlic", "ginger", "jasmine rice"],
        tags=["high_protein"],
        cuisine="Asian",
        prep_minutes=10,
        cook_minutes=15,
        total_minutes=25,
        servings=2,
        calories=450.0,
        protein_g=30.0,
        carbs_g=48.0,
        fat_g=12.0,
        estimated_cost=7.00,
    ),
    Recipe(
        recipe_id=1009,
        title="Egg White Omelette",
        ingredients=["egg whites", "spinach", "tomato", "mushroom", "feta cheese"],
        tags=["vegetarian", "high_protein", "low_carb"],
        cuisine="American",
        prep_minutes=5,
        cook_minutes=8,
        total_minutes=13,
        servings=1,
        calories=180.0,
        protein_g=22.0,
        carbs_g=6.0,
        fat_g=7.0,
        estimated_cost=3.00,
    ),
    Recipe(
        recipe_id=1010,
        title="Quinoa Buddha Bowl",
        ingredients=["quinoa", "chickpeas", "sweet potato", "kale", "tahini", "lemon"],
        tags=["vegetarian", "vegan", "gluten_free", "high_fiber"],
        cuisine="American",
        prep_minutes=10,
        cook_minutes=25,
        total_minutes=35,
        servings=2,
        calories=400.0,
        protein_g=16.0,
        carbs_g=58.0,
        fat_g=12.0,
        estimated_cost=6.50,
    ),
    Recipe(
        recipe_id=1011,
        title="Tuna Wrap",
        ingredients=["canned tuna", "whole wheat tortilla", "lettuce", "tomato", "mayo", "mustard"],
        tags=["high_protein"],
        cuisine="American",
        prep_minutes=8,
        cook_minutes=0,
        total_minutes=8,
        servings=1,
        calories=320.0,
        protein_g=28.0,
        carbs_g=30.0,
        fat_g=10.0,
        estimated_cost=4.00,
    ),
    Recipe(
        recipe_id=1012,
        title="Banana Smoothie",
        ingredients=["banana", "peanut butter", "milk", "protein powder", "ice"],
        tags=["vegetarian", "high_protein"],
        cuisine="American",
        prep_minutes=5,
        cook_minutes=0,
        total_minutes=5,
        servings=1,
        calories=340.0,
        protein_g=25.0,
        carbs_g=40.0,
        fat_g=10.0,
        estimated_cost=3.00,
    ),
    Recipe(
        recipe_id=1013,
        title="Lentil Soup",
        ingredients=["red lentils", "onion", "carrot", "celery", "garlic", "cumin", "vegetable broth"],
        tags=["vegetarian", "vegan", "gluten_free", "high_fiber"],
        cuisine="Middle Eastern",
        prep_minutes=10,
        cook_minutes=30,
        total_minutes=40,
        servings=4,
        calories=220.0,
        protein_g=14.0,
        carbs_g=36.0,
        fat_g=2.0,
        estimated_cost=4.00,
    ),
    Recipe(
        recipe_id=1014,
        title="Beef and Broccoli",
        ingredients=["beef sirloin", "broccoli", "soy sauce", "garlic", "ginger", "cornstarch", "rice"],
        tags=["high_protein"],
        cuisine="Asian",
        prep_minutes=15,
        cook_minutes=15,
        total_minutes=30,
        servings=2,
        calories=500.0,
        protein_g=36.0,
        carbs_g=40.0,
        fat_g=18.0,
        estimated_cost=10.00,
    ),
    Recipe(
        recipe_id=1015,
        title="Caprese Salad",
        ingredients=["fresh mozzarella", "tomato", "basil", "olive oil", "balsamic vinegar"],
        tags=["vegetarian", "gluten_free", "low_carb"],
        cuisine="Italian",
        prep_minutes=10,
        cook_minutes=0,
        total_minutes=10,
        servings=2,
        calories=220.0,
        protein_g=14.0,
        carbs_g=6.0,
        fat_g=16.0,
        estimated_cost=6.00,
    ),
    Recipe(
        recipe_id=1016,
        title="Shrimp Tacos",
        ingredients=["shrimp", "corn tortillas", "cabbage", "lime", "cilantro", "avocado", "chipotle sauce"],
        tags=["gluten_free", "high_protein"],
        cuisine="Mexican",
        prep_minutes=10,
        cook_minutes=10,
        total_minutes=20,
        servings=2,
        calories=360.0,
        protein_g=28.0,
        carbs_g=30.0,
        fat_g=14.0,
        estimated_cost=9.00,
    ),
    Recipe(
        recipe_id=1017,
        title="Peanut Butter Toast",
        ingredients=["whole wheat bread", "peanut butter", "banana", "honey"],
        tags=["vegetarian"],
        cuisine="American",
        prep_minutes=3,
        cook_minutes=2,
        total_minutes=5,
        servings=1,
        calories=300.0,
        protein_g=10.0,
        carbs_g=40.0,
        fat_g=14.0,
        estimated_cost=2.00,
    ),
    Recipe(
        recipe_id=1018,
        title="Chicken Caesar Wrap",
        ingredients=["chicken breast", "romaine lettuce", "parmesan cheese", "caesar dressing", "whole wheat tortilla"],
        tags=["high_protein"],
        cuisine="American",
        prep_minutes=10,
        cook_minutes=15,
        total_minutes=25,
        servings=1,
        calories=420.0,
        protein_g=34.0,
        carbs_g=28.0,
        fat_g=18.0,
        estimated_cost=6.00,
    ),
    Recipe(
        recipe_id=1019,
        title="Vegetable Curry",
        ingredients=["chickpeas", "coconut milk", "spinach", "tomato", "onion", "garlic", "curry powder", "rice"],
        tags=["vegetarian", "vegan", "gluten_free"],
        cuisine="Indian",
        prep_minutes=10,
        cook_minutes=25,
        total_minutes=35,
        servings=4,
        calories=350.0,
        protein_g=12.0,
        carbs_g=45.0,
        fat_g=14.0,
        estimated_cost=5.00,
    ),
    Recipe(
        recipe_id=1020,
        title="Turkey Sandwich",
        ingredients=["turkey slices", "whole wheat bread", "lettuce", "tomato", "mustard", "swiss cheese"],
        tags=["high_protein"],
        cuisine="American",
        prep_minutes=5,
        cook_minutes=0,
        total_minutes=5,
        servings=1,
        calories=350.0,
        protein_g=28.0,
        carbs_g=32.0,
        fat_g=12.0,
        estimated_cost=5.00,
    ),
    Recipe(
        recipe_id=1021,
        title="Mixed Berry Smoothie Bowl",
        ingredients=["mixed berries", "banana", "almond milk", "granola", "chia seeds"],
        tags=["vegetarian", "vegan"],
        cuisine="American",
        prep_minutes=5,
        cook_minutes=0,
        total_minutes=5,
        servings=1,
        calories=280.0,
        protein_g=8.0,
        carbs_g=50.0,
        fat_g=6.0,
        estimated_cost=4.00,
    ),
]

MOCK_RECIPES_BY_ID = {r.recipe_id: r for r in MOCK_RECIPES}


def mock_candidates(k: int = 21) -> list[RecipeCandidate]:
    """Return mock RecipeCandidates from MOCK_RECIPES."""
    out = []
    for i, r in enumerate(MOCK_RECIPES[:k]):
        out.append(
            RecipeCandidate(
                recipe_id=r.recipe_id,
                score=10.0 - i * 0.3,
                reasons=["mock candidate"],
                recipe=r,
            )
        )
    return out


MOCK_PROFILE = UserProfile(
    user_id=1,
    username="mock_user",
    age=30,
    height_feet=5,
    height_inches=8,
    weight_lbs=165.0,
    gender="male",
    goal="weight_loss",
    dietary_preferences=[],
    allergies=[],
    medical_conditions=[],
    budget_level="medium",
    cooking_time="short",
    cuisine_preferences=[],
    disliked_ingredients=[],
)

MOCK_NUTRITION_TARGETS = {
    "daily_calories": 1800.0,
    "protein_g": 120.0,
    "carbs_g": 180.0,
    "fat_g": 60.0,
}
